#!/usr/bin/env bash

PYTHONPATH=.

NODE_URL_GRPC="veganode.example.com:3002"
NODE_URL_REST="https://veganode.example.com"
WALLETSERVER_URL="https://walletserver.example.com"

# used in submit-order:
WALLET_NAME="example_wallet_name"
WALLET_PASSPHRASE="example_wallet_passphrase"

#

export PYTHONPATH
export NODE_URL_GRPC
export NODE_URL_REST
export WALLETSERVER_URL
export WALLET_NAME
export WALLET_PASSPHRASE
