#!/usr/bin/env bash

# Default server configuration used by REST/GRPC/GRAPHQL examples

DATA_NODE_URL_REST="https://api.n06.testnet.vega.xyz/api/v2"
DATA_NODE_URL_GRAPHQL="https://api.n07.testnet.vega.xyz/graphql"
DATA_NODE_URL_GRPC="n07.testnet.vega.xyz:3007"
WALLET_SERVER_URL="https://wallet.testnet.vega.xyz"
MARKET_ID=""
PARTY_ID=""
ASSET_ID=""

export DATA_NODE_URL_GRPC
export DATA_NODE_URL_REST
export DATA_NODE_URL_GRAPHQL
export WALLET_SERVER_URL

export MARKET_ID
export PARTY_ID
export ASSET_ID
